%conFigure   Adjust default figure settings.
%   conFigure(width,aspectRatio) configures future plots to a 
%   particular width (in cm) and aspect ratio (width:height). 
%   conFigure changes the default settings for figures
%   created *after* it is called. By default if called with no 
%   arguments, selects width 11cm for full-width manuscript 
%   figures and 1.4:1 width:height. If:
%-width<15, conFigure will assume you want to make paper 
%   figures and use axis labels (&etc) of size 8. 
%-width>15, conFigure will assume you want to look at figures
%   on your screen and use large text for axis labels etc.
%-aspectRatio is not specified, chooses 1.4:1.
%   All axis labels, titles, etc, use LaTeX as the interpreter 
%   (except for the titles of colormaps, for which the interpreter
%   cannot be set in Matlab/R2018a).
%   conFigure assumes you may be interested in producing .pdf 
%   plots and configures default settings so that print() 
%   produces useful plots.
%Example: try
%        x = 1:10; y = x.^2+2*randn(size(x)); %some data
%  conFigure(5.5,1) %make a square figure that takes half a page-width
%       figure; plot(x,y,'o')
%       xlabel('Pos $x$')
%       ylabel('Pos $y$')
%        title('Science!')
%        print('testWidth5','-dpdf')
%  conFigure(11,3) %a short, full width paper figure
%       figure; plot(x,y,'o')
%        xlabel('Pos $x$')
%       ylabel('Pos $y$')
%       print('testWidth11','-dpdf')
%  conFigure(33) %for viewing results on-screen.
%       figure; plot(x,y,'o')
%        xlabel('Pos $x$')
%        ylabel('Pos $y$')
% Life hack: make a script, containing the command
%   conFigure(33);
%   Name this script startup.m and save it in Documents/MATLAB/
%   Matlab will automatically run startup.m when it launches, and
%   all your plots will look good for display with no further 
%   effort on your part.
%   Limitations: 1) When printing, Matlab often generates spurious
%   warnings that 'The figure is too large for the page and will
%   be cut off.'
%   These warnings can generally be ignored (I do not know why they are
%   generated). An important feature of conFigure is that your figures will
%   appear when printed just as they appear on your screen. If your figure
%   labels are not cut off on your screen, they will be printed correctly.
%   2) The aspect ratio is not implemented perfectly; figure 
%   titles, tick labels, and axis labels will all deform the plot
%   slightly as they compete for space. 
%   JM, Oct 2020.


function conFigure(figWid,aspectRatio) 

if nargin==0
    figWid=40;
    aspectRatio = 1.4;
elseif nargin==1
    aspectRatio = 1.4;
end

%set defaults
paperTextSize = 10; %for paper figures
displayTextSize = 30; %for display figures
paperMarkerSize=3;
displayMarkerSize=12;

if figWid<15
    set(groot, 'DefaultLineLineWidth', 1, ...
        'DefaultAxesBox', 'off',...
        'DefaultFigureUnits','centimeters', ...
        'defaultFigurePosition', [30 20 figWid figWid/aspectRatio], ...
        'DefaultLineMarkerSize', paperMarkerSize, ...
        'DefaultAxesLineWidth', 1, ...
        'DefaultAxesTickLength',[0.015 0.015],...
        'defaultfigurecolor',[1 1 1],...
        'defaultFigurePaperUnits','centimeters',...
        'defaultFigurePaperPosition',[30 20 figWid figWid/aspectRatio],...
        'defaultFigurePaperType','<custom>',... 
        'defaultFigurePaperSize',[figWid figWid/aspectRatio],...
        'DefaultAxesFontSize', paperTextSize, ...
        'DefaultTextFontSize', paperTextSize, ...
        'DefaultTextInterpreter', 'latex', ...
        'DefaultLegendInterpreter', 'latex', ...
        'DefaultColorbarTickLabelInterpreter', 'latex', ...
        'DefaultAxesTickLabelInterpreter','latex');
else
        set(groot, 'DefaultLineLineWidth', 1, ...
        'DefaultAxesBox', 'off',...
        'DefaultFigureUnits','centimeters', ...
        'defaultFigurePosition', [25 20 figWid figWid/aspectRatio], ...
        'DefaultLineMarkerSize', displayMarkerSize, ...
        'DefaultAxesLineWidth', 2, ...
        'DefaultAxesTickLength',[0.015 0.015],...
        'defaultfigurecolor',[1 1 1],...
        'defaultFigurePaperUnits','centimeters',...
        'defaultFigurePaperPosition',[25 20 figWid figWid/aspectRatio],...
        'defaultFigurePaperType','<custom>',...
        'defaultFigurePaperSize',[figWid figWid/aspectRatio],...
        'DefaultAxesFontSize', displayTextSize, ...
        'DefaultTextFontSize', displayTextSize, ...
        'DefaultTextInterpreter', 'latex', ...
        'DefaultLegendInterpreter', 'latex', ...
        'DefaultColorbarTickLabelInterpreter', 'latex', ...
        'DefaultAxesTickLabelInterpreter','latex');
end